name: Sri Lanka Advance Box Office

on:
  schedule:
    - cron: "30 1 * * *"   # 7:00 AM IST
    - cron: "0 7 * * *"    # 12:30 PM IST
    - cron: "30 12 * * *"  # 6:00 PM IST
    - cron: "0 17 * * *"   # 10:30 PM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install Dependencies
        run: |
          pip install cloudscraper

      - name: 🚀 Run Advance Box Office Script
        run: |
          python "srilankadailyadv.py"

      - name: 💾 Commit & Push Updated Files
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Auto update: Sri Lanka Advance BO $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
